// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://roosavhfsxqxaylshhdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvb3Nhdmhmc3hxeGF5bHNoaGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMTUzNTgsImV4cCI6MjA3Mjc5MTM1OH0.xxl8o3fXdyyBuLXLp1vsoB7PWI6CeAK2CavHLyL7Vbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});